keys:
  - &avy age13y7t2j7l2su00e5lqm5zslug8czd0hvjjqapgyjxaumwzz0yvfzsjpz084
  - &gpg 0x0F7A57CF72410272
  - &aws arn:aws:kms:us-east-2:513483285585:key/mrk-3e9325e56b2444fea58e7aa1f7bf752b
  - &pi1 age16msd9s7x6v3fa0n4plz8802vgkadgtqku8qzuat0vqkrl5vnyfps77t4vm
  - &pi1-avy age1t2zq6xsa3al6sq3ctuuy3f9zvfzvh823k672cjqye9la0st8tufsqrw5jk
  - &apollo1 age1p0qtfzkuqghlmjwttnrcp7735agrtwwkfq5jnguszwar754h540swl5dyf
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *avy
          - *pi1
          - *pi1-avy
          - *apollo1
        pgp:
          - *gpg
        aws:
          - *aws
