# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = lib.mkForce "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
    fsType = "ext4";
  };

  swapDevices = [ ];

  hardware.deviceTree = {
    enable = true;

    # Pine64+ (2GB RAM variant), not the base 1GB Pine64.
    name = "allwinner/sun50i-a64-pine64-plus.dtb";

    overlays = [
      {
        name = "pine64-wifi";
        dtsFile = ./dts/pine64-wifi-overlay.dts;
      }
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
