name: build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  checks:
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            system: x86_64-linux
          - runner: macos-latest
            system: aarch64-darwin
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:ci
          ping: 100.117.24.61
      - name: setup xilo for caching
        uses: stubbedev/xilo@v0
        with:
          url: https://cache.avyay.in
          cache: default/main
          token: ${{ secrets.XILO_TOKEN }}

      - name: Build devshell
        run: nix build --no-link .#devShells.$(nix eval --raw --expr 'builtins.currentSystem').default
      - name: Push devshell to Cache
        run: xilo push default/main ./result

      - name: Run om ci
        run: |
          nix develop --command om ci run \
            --extra-access-tokens ${{ secrets.GITHUB_TOKEN }} \
            --systems "${{ matrix.system }}" \
            -- --accept-flake-config
      - name: Push to Cache
        run: xilo push default/main ./result
