syncthing:
    guipass: ENC[AES256_GCM,data:lQUDPs8b9+Bh3j5kM6s1,iv:BDplSTJmnuxMqMMVREZ6Vy1g1sDHwqfIigYLwllwQQA=,tag:85x+U9fwION3PnfQfENeyQ==,type:str]
miniflux:
    adminpass: ENC[AES256_GCM,data:91qA7Go5mBze/Fv0gtE=,iv:g/2jPeCPcrJt03gOq43mPICjDaPVBNa59gqwjHrT5Gw=,tag:LlGAlogtn4R7jdwu41IPFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZ0QrTkxNVjB2bElrSDlx
            RWR3SUxwbnNYLzc5dDJ2RGg5ZFlHdHRnWUdrCkpCcTlPamIzWlRXMHZyTlVHL0dF
            a3FGTkt3bHgvQ2UyRFJ4c2lFazd3MGcKLS0tIGEvcnVlQmpzSnBKczJxeUc4MkIx
            d2draG1IRm9sNXpTOVgzVFZja2RvYkUKz9mzEbqycLjEftOpf69Ny9ezkZTVt8/I
            0j1wyNftCv93C7AJwXrhFxOnLLbnuyJYYdVK7zMG0HdlOjPTm0K32w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13y7t2j7l2su00e5lqm5zslug8czd0hvjjqapgyjxaumwzz0yvfzsjpz084
    lastmodified: "2026-06-08T18:58:36Z"
    mac: ENC[AES256_GCM,data:tZz7qInZIiKrsPuGKpKqS+xQ6dqWXCXFyn5/7gxhbA7QTHpC3vbhtUrpc3/AtR5vLbu4DcPnyNburLnjvPois26gVkNEGrP4O5UXb+Xtnzlep1tqP5r8KcpZGux/2QsY9j0IxJRuuDPe4S09NlK94fMbD9CpTzk0yNdbvXUXPwI=,iv:yyPUFKlcYBfMoPcaavv6cNJgdHQwxPLnCT+/NXMicyc=,tag:RIHtq+77hmwF7hvrvwf+cQ==,type:str]
    pgp:
        - created_at: "2026-06-08T18:56:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DgkQWRaqoafoSAQdApMW2x5dDwwtFe9Y/1hpOVC0vihdDj7Ux9qc7QfPS9yow
            hbDwdij4N7R6bWG3ygZ6AZqjJSL6mfKE1cyWhlMXz184nYAcr7g0loCJarAG8JFD
            0l4BjV21XxojuUA58cDjfLGhaiNZaF/Uk4PqR5y0q4QGQrsCcp+pDtA8Ftsw7g6T
            A/kaanOK0QguYkusEGIdpFwHzU13XmWRBWKAYkLBoX/8VLRH4krqWNOisCgYqVTv
            =oNEv
            -----END PGP MESSAGE-----
          fp: "0x0F7A57CF72410272"
    unencrypted_suffix: _unencrypted
    version: 3.13.1
