syncthing:
    guipass: ENC[AES256_GCM,data:lQUDPs8b9+Bh3j5kM6s1,iv:BDplSTJmnuxMqMMVREZ6Vy1g1sDHwqfIigYLwllwQQA=,tag:85x+U9fwION3PnfQfENeyQ==,type:str]
miniflux:
    admin_credentials: ENC[AES256_GCM,data:Ak1LEG8wnvA+lM0tVUVRuwgOYoQendUqxw2Inuuhz8BXgCrsegUOIlaneu3Lz5zkxg==,iv:fO73V+/ct3P29+uET3tycstOzjva2l9x1ysZ2c1vWUA=,tag:z+3C0CKSJZVb8liFwbSOQg==,type:str]
    oauth_client_id: ENC[AES256_GCM,data:Rsn8rQOFwdSGTEyq+BS8zlh7gg+Veuzx6w==,iv:QDYL4s/FOyozNFcUw/08vcS8M8mMCQBnqvyxL0qFnN0=,tag:0WWRf37e8sEThbFynptxrw==,type:str]
    oauth_client_secret: ENC[AES256_GCM,data:Zh7BsTKcgU7J9VlvyQ2aNc+1UobaY1UfqskSCfgBx+PKzHyibI1IWw53YM4p5fo=,iv:V4sscbYy/2R1djC0N/tG7ePVe9pFEcw6fzAv/9CRfFo=,tag:/3zUUQpVcpU16044F9VRXg==,type:str]
speedtest-tracker:
    app_key: ENC[AES256_GCM,data:+J/whdqWlbUINc+uUTU0nAcWWaoxGfb08X3M1Vueaa8fWkFYiCrsVNnsyPG/5AlfD4gH,iv:PsKT4AawTQJTC09o2WAcvTHtJ8TbuAlQ6Fbe+p0hj1o=,tag:G49DEgV4mChrLAE30ZiFUg==,type:str]
xilo:
    env: ENC[AES256_GCM,data:8oNv4+k0tHVe1+9sAEqfdk4bR5n6Ruye2CUYgceEeGfuVJmP7NmxQ1GSsgegdOxtK7tlWZ/gcvQ4gvVAwwIBfGB+cgKUmIKcdcyNeVtZ9EFJnVAhiktu8QBdEBWsuaItOfktwTN0nLRE3Etw7cIDy0tY0tVIcHbEERKRjvdltTq4zjbc9XYxXcc/l+g2QFUXaYVJqbkKqifeDOCrmXY2saQxbRnmfsdWVe+FIBXu2IDbFZ5Pe2tvqnEIHwE=,iv:dg1cJHmF9BWUuyZGpAHPAl33/Y44C+Yg/YYDVuHwAhQ=,tag:Lac5gwhBszFaYyXZUfr1ng==,type:str]
    gcs_access_key: ENC[AES256_GCM,data:Fcwr+fsAEnTL5B7BKw7kWPru9a/EBc00gFBkJQSLbKKrh786Rd2p7AmrC6DEn4QMi59WqfFU8yk+QjaiQA==,iv:fhTpP7rnts7UAjjZPWGMb/c7ysOMNTZwqt31XknrxhM=,tag:Py1PAHPte+cNCXpYbKa0sQ==,type:str]
    gcs_secret_key: ENC[AES256_GCM,data:pkm5IdybhixhjGudT8SnYrMbhi0RUUnjsBEi6xPErwFTpsgF6Hbehg==,iv:Xz8ULtjXk2fyl4yVljcyEieGuM9Tw0co0eZ/fZTSGIg=,tag:7gcDZLjA0s13onG3ijwsUA==,type:str]
retrom:
    igdb_client_id: ENC[AES256_GCM,data:rRuhKMjWDjkuA8Wzay2zlmCgQ7LYP4jc0B38CFol,iv:vsd+LK9D+EzYJmGS/2uhviVdsFO56ZfJ0qEKJ6MN7Ck=,tag:/8C9pMDKCaEVOAIQteABcA==,type:str]
    igdb_client_secret: ENC[AES256_GCM,data:3cH6PeCwdBPBffnXEb4sCgEjBvbjABZDkd9Iry3g,iv:47wlCTtTHPVBgnsah4/2ybAQtrD6tbGWf95zqlCB/5o=,tag:FwdgpKw4zt7jne5Q0qzXWQ==,type:str]
restic:
    repository_password: ENC[AES256_GCM,data:qZGS7DcksTYYfYw0vnqSUqBPgEv6VkJ7cz2VjI9I,iv:Pm/bRZJlESHBpXq9ORogRG9O6wxUNv08BmwxaO3BRaY=,tag:CkWJNupoCGrsldmiVjQXKw==,type:str]
    b2_credentials: ENC[AES256_GCM,data:MZc39p5cazze+KvWkZPQCFpwx5J7ttvmUQ1Nqu6FFV1/pNA3cNLCVx6RtLidxOsGVUggYJm7a0RKC2bIKry2GkAuxkJ1dujP/R0h/6NwfGmt4vUsLFSx,iv:lqk4Sb5yffxO6u0g0BuA4DMHimCmCkzJMNIf2zxlZXI=,tag:xHa2YxvPEN5muX2nu5DXLA==,type:str]
isponsorblocktv:
    living_room_tv_screen_id: ENC[AES256_GCM,data:lcbHnl+ScAxEBnq4MD+SJ82xSsFsiq4dW6Qfv0fO3tF/7bkoOYtOZNEGtyMgPqlas06Xnj5rIIJCa3Bhd+fFXA==,iv:P81eK2eRYEt6AkokQcw77Cb0syZv2uwK80thrBp1v6E=,tag:2MRYjMc6N3E6P2D83mp1SQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdEdqcWZiU3FWZDV2TmN2
            bnBWS2h6SUdVeTZyb1Iyc0NDQ1czaWw1U0dZClV4cDNLVkl5RjE5S1VGR2dZc2VD
            bnRDZGdybWZZdjB3RHdnVjlpcldDTDAKLS0tIFpmTEROcVJGTTdWSll2N1B4K2t1
            bUFtVDd5QlVCMy90endyZnpDVmtGc0EK44ixGCCr1iAvZpPowglHeHTBwof3zdEP
            s8Xc4vSR0hbFguCJecDxgrAkU3h11eEEZpqCYGLvxSX3QqPdYhXq+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13y7t2j7l2su00e5lqm5zslug8czd0hvjjqapgyjxaumwzz0yvfzsjpz084
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTC83bHE4OUtCcW9VTm1J
            SjlLNWIxcGhmTmtOU3QvMEp3N0lhTnNWNnlFCmx0TEIyS3dpczJuM21LSTFobVV0
            Qm5lOFhIRkdyT0QxSGFRV2s1UkJMZVkKLS0tIHlab05XUG84bnVUQ3pZTEVYMU5V
            amc1R2o3aFNvQW5RSUI5YVh2TkpPZWMKmuVxL9AuhpHDu8RPOoU+MT0Biywf4fl8
            h/TKxz7Ux3B3jixKJ4GPovLDyH2RWWuuiz9wez+4wkiUZNkvx61Opg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16msd9s7x6v3fa0n4plz8802vgkadgtqku8qzuat0vqkrl5vnyfps77t4vm
    lastmodified: "2026-08-05T01:55:22Z"
    mac: ENC[AES256_GCM,data:3PMv+GWK1jthWlWYFv9Mkn70RHomktgGnYrTQ6pS7uCAmcDpLNJqoPlO+9lFwxUN/43K+mCRo1EMfHXd/u4rh3hQiPDNSB0DlZO2KcQCuegebqTy6L0ziCa4jsoOPA6yPjG5PsrOqbRc4T5pAwq4JzHcnUpkqwTO8kIpGXsqRhU=,iv:/jMfmdvg6pXhTnRdP7A/eC1HTlY/kBtAIoaWifkHC8c=,tag:LTXXhct39TcYLFteFXv+Cg==,type:str]
    pgp:
        - created_at: "2026-07-15T15:08:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DgkQWRaqoafoSAQdAVtJbLHi+RexHfj10NIphHRRiDFw2jZXxPRwm0p1q+1Aw
            pcGnsu796QrnmTGjLngV2QPjoI6TjCCgbzKYvwedYtz2EpcP8z5zAjCCJhXU5DVG
            0l4BndYBUTKjRYV8MzfyTP3X02UtEtLeEok4bIYqEveNVfzQnrXpLPyoKLpE7CHI
            weQhRVOg7QnyhoEbGIS511wojLUENi9vIcPt3NmwYFl4eIfLshGLr0qZXwbkS271
            =R5sj
            -----END PGP MESSAGE-----
          fp: "0x0F7A57CF72410272"
    unencrypted_suffix: _unencrypted
    version: 3.13.3
