syncthing:
    guipass: ENC[AES256_GCM,data:lQUDPs8b9+Bh3j5kM6s1,iv:BDplSTJmnuxMqMMVREZ6Vy1g1sDHwqfIigYLwllwQQA=,tag:85x+U9fwION3PnfQfENeyQ==,type:str]
miniflux:
    admin_credentials: ENC[AES256_GCM,data:Ak1LEG8wnvA+lM0tVUVRuwgOYoQendUqxw2Inuuhz8BXgCrsegUOIlaneu3Lz5zkxg==,iv:fO73V+/ct3P29+uET3tycstOzjva2l9x1ysZ2c1vWUA=,tag:z+3C0CKSJZVb8liFwbSOQg==,type:str]
    oauth_client_id: ENC[AES256_GCM,data:Rsn8rQOFwdSGTEyq+BS8zlh7gg+Veuzx6w==,iv:QDYL4s/FOyozNFcUw/08vcS8M8mMCQBnqvyxL0qFnN0=,tag:0WWRf37e8sEThbFynptxrw==,type:str]
    oauth_client_secret: ENC[AES256_GCM,data:Zh7BsTKcgU7J9VlvyQ2aNc+1UobaY1UfqskSCfgBx+PKzHyibI1IWw53YM4p5fo=,iv:V4sscbYy/2R1djC0N/tG7ePVe9pFEcw6fzAv/9CRfFo=,tag:/3zUUQpVcpU16044F9VRXg==,type:str]
speedtest-tracker:
    app_key: ENC[AES256_GCM,data:+J/whdqWlbUINc+uUTU0nAcWWaoxGfb08X3M1Vueaa8fWkFYiCrsVNnsyPG/5AlfD4gH,iv:PsKT4AawTQJTC09o2WAcvTHtJ8TbuAlQ6Fbe+p0hj1o=,tag:G49DEgV4mChrLAE30ZiFUg==,type:str]
xilo:
    env: ENC[AES256_GCM,data:8oNv4+k0tHVe1+9sAEqfdk4bR5n6Ruye2CUYgceEeGfuVJmP7NmxQ1GSsgegdOxtK7tlWZ/gcvQ4gvVAwwIBfGB+cgKUmIKcdcyNeVtZ9EFJnVAhiktu8QBdEBWsuaItOfktwTN0nLRE3Etw7cIDy0tY0tVIcHbEERKRjvdltTq4zjbc9XYxXcc/l+g2QFUXaYVJqbkKqifeDOCrmXY2saQxbRnmfsdWVe+FIBXu2IDbFZ5Pe2tvqnEIHwE=,iv:dg1cJHmF9BWUuyZGpAHPAl33/Y44C+Yg/YYDVuHwAhQ=,tag:Lac5gwhBszFaYyXZUfr1ng==,type:str]
    gcs_access_key: ENC[AES256_GCM,data:Fcwr+fsAEnTL5B7BKw7kWPru9a/EBc00gFBkJQSLbKKrh786Rd2p7AmrC6DEn4QMi59WqfFU8yk+QjaiQA==,iv:fhTpP7rnts7UAjjZPWGMb/c7ysOMNTZwqt31XknrxhM=,tag:Py1PAHPte+cNCXpYbKa0sQ==,type:str]
    gcs_secret_key: ENC[AES256_GCM,data:pkm5IdybhixhjGudT8SnYrMbhi0RUUnjsBEi6xPErwFTpsgF6Hbehg==,iv:Xz8ULtjXk2fyl4yVljcyEieGuM9Tw0co0eZ/fZTSGIg=,tag:7gcDZLjA0s13onG3ijwsUA==,type:str]
retrom:
    igdb_client_id: ENC[AES256_GCM,data:rRuhKMjWDjkuA8Wzay2zlmCgQ7LYP4jc0B38CFol,iv:vsd+LK9D+EzYJmGS/2uhviVdsFO56ZfJ0qEKJ6MN7Ck=,tag:/8C9pMDKCaEVOAIQteABcA==,type:str]
    igdb_client_secret: ENC[AES256_GCM,data:3cH6PeCwdBPBffnXEb4sCgEjBvbjABZDkd9Iry3g,iv:47wlCTtTHPVBgnsah4/2ybAQtrD6tbGWf95zqlCB/5o=,tag:FwdgpKw4zt7jne5Q0qzXWQ==,type:str]
restic:
    repository_password: ENC[AES256_GCM,data:qZGS7DcksTYYfYw0vnqSUqBPgEv6VkJ7cz2VjI9I,iv:Pm/bRZJlESHBpXq9ORogRG9O6wxUNv08BmwxaO3BRaY=,tag:CkWJNupoCGrsldmiVjQXKw==,type:str]
    b2_credentials: ENC[AES256_GCM,data:MZc39p5cazze+KvWkZPQCFpwx5J7ttvmUQ1Nqu6FFV1/pNA3cNLCVx6RtLidxOsGVUggYJm7a0RKC2bIKry2GkAuxkJ1dujP/R0h/6NwfGmt4vUsLFSx,iv:lqk4Sb5yffxO6u0g0BuA4DMHimCmCkzJMNIf2zxlZXI=,tag:xHa2YxvPEN5muX2nu5DXLA==,type:str]
isponsorblocktv:
    living_room_tv_screen_id: ENC[AES256_GCM,data:lcbHnl+ScAxEBnq4MD+SJ82xSsFsiq4dW6Qfv0fO3tF/7bkoOYtOZNEGtyMgPqlas06Xnj5rIIJCa3Bhd+fFXA==,iv:P81eK2eRYEt6AkokQcw77Cb0syZv2uwK80thrBp1v6E=,tag:2MRYjMc6N3E6P2D83mp1SQ==,type:str]
lard:
    env: ENC[AES256_GCM,data:9FZtoi3wDewNw8Zomh0Mhzbj8M/EUzo4MDk65tWWbEJUSLKz/xDfzVw3NnHiuC5xG7nxdxhl6Tvej8WNpAHD6g==,iv:g32rYzv0NGnybuyksoHWqnFyZlUk/aIaQ7LV7jfmXy4=,tag:csBVnTPH2FJCZyXT0V5zmQ==,type:str]
asterisk:
    cisco7945_password: ENC[AES256_GCM,data:yBQvOBv+vVfm3/utFUMdwpNgBaa3lGDMnTh/Flfp73w=,iv:EDe6xkrVUyfR3pf+03JUSIavc02ufSMjTIcsoHd7hz0=,tag:CWI19O6xKTc9JdES2KderA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bVRra1FhZHM4RXEyZnVT
            RHlTeUs3QW9qOHZpQmVLZDNONDFXSDJGc1FJCk82L3gxaGkwaXA5dG1paU4wWXF0
            T1VZSTlCMEhrSk1nQVpxNW8vcUZsbWsKLS0tIGtxUmdtWHQrZ3poY0E0bkhDOHgv
            NkRtdGc1RWhISEpwdlE4bXRYM2N2OFEKGAeS1oMaLUfS49/pnd6NxC4Kf+F6xV4K
            j5Ts7rcYUr/kQ6WKUM7r8vT3nmSC+Be0m3Y1V9+Euo8KXwCmg+VNoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13y7t2j7l2su00e5lqm5zslug8czd0hvjjqapgyjxaumwzz0yvfzsjpz084
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aWxDRzNHczQ1T3ovVWx4
            SGNhd2dTSHlhdUZLQ2Zid1Jxdnh2VEZLZUJNCnRCbnN0YjB6R2luamdSME9CR25r
            ZTl0c3ZHaHp2YmhrVGlIWW94bzdWZ2sKLS0tIFVNcGFRd2ZET3I0Y3AwMjBOQldi
            YUFkNDdzbVV6OTFZUHNyQnBJMUI1dUkKgZ+gzkuvHzUracUp9kQZv38C/TuoP58g
            XL5KUPFMJbSeuxr6eaC+mOjj1Dvyp7FRD+fyICPrbgP+X1dwR9+r8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16msd9s7x6v3fa0n4plz8802vgkadgtqku8qzuat0vqkrl5vnyfps77t4vm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTjA0dEhSb2xOZGd1OTBP
            TXpiSjJwTERBYVNmTHIveTM0RmhKNE5VRENrCkdna1I4b2NLOXA2VFBFd3c1WUsy
            bTRkM2V3RnRqajMzN2RiWlFqcSsxd0EKLS0tIDcreGZtTTNRaEJ5dTU2KzJlYjNC
            dTRiTG5DaEVPQk14YXFPdDRad1RBY1kKTI352/OgfoE+g3EuObG5yG8L2Wxmv0C5
            MjD6QoRiiWW7Rc7t3S9b9j5Aqva4fpLTDJj3sKF5FY88CIgeBuZiEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t2zq6xsa3al6sq3ctuuy3f9zvfzvh823k672cjqye9la0st8tufsqrw5jk
    lastmodified: "2026-08-11T02:58:09Z"
    mac: ENC[AES256_GCM,data:R3Ep5y2yT2o9fkF+4SHdiCJzOsoabQZZOhQRmyPYlrSI7Le0xgn7MqKOc37AmVQgcY5qVkDznf5bcJmYOJ5+CRrYw/BNM8A6+XVji9J8GXasvmCVgFcMzf706sUyjibRlf6JYweTamSxmfKWAC64W4lGY1QR68ojXhQmUuRly5o=,iv:EsH8lMLiZ4xCALQLc5QEVM9a5oghvWtXF1HnR4pb4P0=,tag:5K4fjeaKPE76H19yej+xmg==,type:str]
    pgp:
        - created_at: "2026-08-13T19:50:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DgkQWRaqoafoSAQdAoB3kzfCV1jJiYaguBDXAfO2hNF2QM/KFPsfAN1jTjWww
            xSDb/+T4P7Z++CaB7uT5O/ePBe/P/iTMByRNoowLypc4ZbP8aHpm4TDOslutW7X6
            0l4BV343oIiyUaBn55FQa0fVRhpCgEOp9dOwK3gCYFyC1FeXojIdJ9uGMr0OqxUN
            nYz7L1C+slpLJStpm1izCW0bqsEBZJvTlrgCSy2Q8AOP+YYOi7q3nPVJwhh+5eZ+
            =2s1N
            -----END PGP MESSAGE-----
          fp: "0x0F7A57CF72410272"
    unencrypted_suffix: _unencrypted
    version: 3.13.3
